slam_toolbox:
  ros__parameters:

    # -----------------------------
    # Frames & Topics
    # -----------------------------
    use_sim_time: true
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # -----------------------------
    # Mode
    # -----------------------------
    mode: localization
    use_map_saver: true

    # -----------------------------
    # Map Settings
    # -----------------------------
    resolution: 0.05
    map_update_interval: 2.0

    # -----------------------------
    # TF / Timing
    # -----------------------------
    transform_publish_period: 0.02
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    minimum_time_interval: 0.1

    # -----------------------------
    # Motion Thresholds  (LOW for quick init)
    # -----------------------------
    minimum_travel_distance: 0.10
    minimum_travel_heading: 0.10

    # -----------------------------
    # Laser Limits
    # -----------------------------
    min_laser_range: 0.0
    max_laser_range: 20.0
    throttle_scans: 1

    # -----------------------------
    # Scan Matching
    # -----------------------------
    use_scan_matching: true
    use_scan_barycenter: true
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0

    # -----------------------------
    # Loop Closing
    # -----------------------------
    do_loop_closing: true
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_minimum_response_fine: 0.45

    # -----------------------------
    # Correlation
    # -----------------------------
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # -----------------------------
    # Solver
    # -----------------------------
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_loss_function: None

    # -----------------------------
    # Misc
    # -----------------------------
    debug_logging: false
    enable_interactive_mode: true
    stack_size_to_use: 40000000

